name: Deploy to cPanel Servers

on:
  push:
    branches:
      - main

jobs:
  deploy_bhaighat:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Bhaighat Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 1588
          script: |
            cd /home/cityxper/public_html/
            git pull --rebase
            php artisan optimize:clear
            php artisan optimize
